# Generated by Django 4.1.7 on 2023-03-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default='', max_length=64, verbose_name='Id')),
                ('response', models.TextField(default='', verbose_name='Ответ retrme')),
            ],
            options={
                'verbose_name': 'Бд',
                'verbose_name_plural': 'Бд',
            },
        ),
    ]
